import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const helvetica = localFont({
	src: [
		{ path: "../public/fonts/Helvetica-Black.otf", weight: "900" },
		{ path: "../public/fonts/Helvetica-Bold.ttf", weight: "700" },
		{ path: "../public/fonts/Helvetica.ttf", weight: "500" },
		{ path: "../public/fonts/Helvetica-Light.ttf", weight: "300" },
	],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
